#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────


# Values live in the repo-root .env regardless of where this is run from.
ENV_FILE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/.env"

TOTAL_STAGES=5

banner "Crafter Status setup"

# ── 1. GitHub SSO in Clerk, with read:org ─────────────────────────────────
stage "Clerk: sign in with GitHub"
say "Access is gated on membership of the crafter-station GitHub org, which we"
say "check with the user's own token. That needs the read:org scope, and custom"
say "scopes require your own GitHub OAuth app rather than Clerk's shared one."
printf '\n'
open_url "https://dashboard.clerk.com/~/user-authentication/sso-connections"
step "Add connection → For all users → choose GitHub."
step "Turn ON 'Use custom credentials'."
step "Copy the Authorization callback URL it shows you, and keep this tab open."
printf '\n'
pause "Got the callback URL? Press Enter to open GitHub."
open_url "https://github.com/settings/developers"
step "New OAuth App. Name it 'Crafter Status'."
step "Homepage URL: https://wspstatus.crafter.run"
step "Authorization callback URL: paste the one Clerk gave you."
step "Register, then Generate a new client secret."
printf '\n'
step "Back in the Clerk tab: paste the Client ID and Client Secret."
step "In the Scopes field add:  read:org"
step "Save."
printf '\n'
note "read:org is what lets the membership check see private org members."
pause "Saved in Clerk?"

# ── 2. Clerk OAuth server for MCP ─────────────────────────────────────────
stage "Clerk: OAuth server for MCP"
say "Claude, ChatGPT and Codex register themselves with your authorization"
say "server on the fly, so that has to be switched on explicitly."
printf '\n'
open_url "https://dashboard.clerk.com/~/oauth-applications"
step "Toggle ON 'Dynamic client registration'."
step "Set the default scopes to:  profile email"
printf '\n'
note "Default scopes matter: some clients omit the scope parameter entirely when"
note "they register, and a token with no scopes is rejected on the way in."
warn "DCR opens a public registration endpoint. That is the price of one-click"
warn "connection from hosted clients; every token still passes the org check."
pause "Dynamic client registration enabled?"

# ── 3. Clerk webhook → users mirror ───────────────────────────────────────
stage "Clerk: user webhook"
say "Keeps the local users table in step with Clerk. Clerk stays the source of"
say "truth; this is only so tokens have a row to hang off."
printf '\n'
open_url "https://dashboard.clerk.com/~/webhooks"
step "Add Endpoint."
step "URL: https://wspstatus.crafter.run/api/webhooks/clerk"
step "Subscribe to: user.created, user.updated, user.deleted"
step "Create, then copy the Signing Secret (starts whsec_)."
printf '\n'
ask_secret CLERK_WEBHOOK_SIGNING_SECRET "Paste the signing secret:"
if [[ -n "$CLERK_WEBHOOK_SIGNING_SECRET" ]]; then
  write_env CLERK_WEBHOOK_SIGNING_SECRET "$CLERK_WEBHOOK_SIGNING_SECRET"
  printf '
'
  warn "this also has to be set on the deployed web service in Dokploy —"
  warn "the .env here only covers local development"
else
  SKIPPED+=("CLERK_WEBHOOK_SIGNING_SECRET (add it to .env when you create the webhook)")
  warn "skipped; the app runs without it, but the users table won't self-update"
fi

# ── 4. Shared secret between web and ingestor ─────────────────────────────
stage "Internal worker secret"
say "The dashboard calls the ingestor's private control API with a shared secret."
say "Nothing else uses it, so we can just generate one."
printf '\n'
if command -v openssl >/dev/null 2>&1; then
  GENERATED=$(openssl rand -base64 36 | tr -d '\n/+=' | cut -c1-44)
else
  GENERATED=$(head -c 48 /dev/urandom | base64 | tr -d '\n/+=' | cut -c1-44)
fi
write_env INGESTOR_TOKEN "$GENERATED"
note "Both apps read INGESTOR_TOKEN from .env, so they already agree."
warn "When you deploy, set the same value on BOTH services and never expose"
warn "the ingestor's port publicly."
pause

# ── 5. Pair WhatsApp ──────────────────────────────────────────────────────
stage "Pair WhatsApp"
say "The last step needs your phone, and it happens on the deployed dashboard."
printf '
'
open_url "https://wspstatus.crafter.run/settings"
step "Sign in with GitHub (you must be in the crafter-station org)."
step "Press 'Pair WhatsApp' and wait for the QR to appear."
step "On your phone: WhatsApp -> Settings -> Linked devices -> Link a device."
step "Scan it. The status badge flips to 'connected'."
step "Press 'Refresh group list', then switch on the groups you want summarized."
printf '
'
note "To run it locally instead: bun run ingestor and bun run web, then use"
note "http://localhost:3000/settings."
printf '
'
warn "Whichever account scans the QR is the account whose groups get mirrored,"
warn "and whatsapp-web.js is against WhatsApp's terms — use a number you are"
warn "willing to lose."
pause "Done?"

finish
